# Ejemplo de github action para probar python
# Docs: https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions
name: Example CI

on:
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests Users
        working-directory: ./usuarios
        env:
          DATABASE_URL: sqlite:///users.db
        run: |
          pip install -r requirements.txt
          pip install pipenv
          coverage run -m unittest tests/test_users.py -v
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
          pytest --cov=src -v -s --cov-fail-under=80
