# Ejemplo de github action para probar python
# Docs: https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions
name: Example CI

on:
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests Users
        working-directory: ./usuarios
        env:
          DATABASE_URL: sqlite:///users.db
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          coverage run -m unittest tests/test_users.py -v
          coverage report --fail-under=80