name: PipeLine Integración

on:
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests Usuarios
        working-directory: ./usuarios
        env:
          DATABASE_URL: sqlite:///users.db
        run: |
          pip install -r requirements.txt
          coverage run -m --omit="*/usr/lib/*" unittest discover -s tests -v
          coverage report --fail-under=80
      - name: Run Tests Trayectos
        working-directory: ./trayectos
        env:
          DATABASE_URL: sqlite:///trayectos.db
        run: |
          coverage run -m --omit="*/usr/lib/*" unittest discover -s tests -v
          coverage report --fail-under=80
      